import {Provider, Review} from '../models/provider.model';

export function createSvgAvatar(
  initials: string,
  bgColor: string,
  textColor: string,
  iconChar: string
): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" width="120" height="120">
    <defs>
      <linearGradient id="grad-${bgColor.replace('#', '')}" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="${bgColor}" />
        <stop offset="100%" stop-color="#1c1917" stop-opacity="0.8" />
      </linearGradient>
    </defs>
    <rect width="120" height="120" rx="60" fill="url(#grad-${bgColor.replace('#', '')})" />
    <circle cx="60" cy="60" r="54" fill="none" stroke="rgba(255,255,255,0.2)" stroke-width="3" />
    <text x="60" y="66" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" font-size="34" font-weight="bold" fill="${textColor}" text-anchor="middle" dominant-baseline="middle">${initials}</text>
    <g transform="translate(74, 74)">
      <circle cx="16" cy="16" r="16" fill="#f59e0b" stroke="#ffffff" stroke-width="2" />
      <text x="16" y="21" font-size="14" text-anchor="middle">${iconChar}</text>
    </g>
  </svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

interface RawSeedProvider {
  id: string;
  fullName: string;
  photoUrl: string;
  phoneNumber: string;
  skill: Provider['skill'];
  customSkill?: string;
  location: string;
  availability: Provider['availability'];
  status: Provider['status'];
  bio?: string;
  experienceYears?: number;
  createdAt: string;
  approvedAt?: string;
  averageRating: number;
  reviewCount: number;
}

const RAW_PROVIDERS: RawSeedProvider[] = [
  {
    id: 'prov-01',
    fullName: 'K. Murugan (முருகன்)',
    photoUrl: createSvgAvatar('KM', '#b45309', '#ffffff', '⚡'),
    phoneNumber: '9840123456',
    skill: 'Electrician',
    location: 'Thanjavur (தஞ்சாவூர்)',
    availability: 'Available Now',
    status: 'approved',
    bio: '12 years experience in house wiring, motor pump starters, inverter setups, and emergency breakdown repairs.',
    experienceYears: 12,
    createdAt: '2026-07-10T09:00:00.000Z',
    approvedAt: '2026-07-10T11:00:00.000Z',
    averageRating: 4.8,
    reviewCount: 3,
  },
  {
    id: 'prov-02',
    fullName: 'S. Selvam (செல்வம்)',
    photoUrl: createSvgAvatar('SS', '#0369a1', '#ffffff', '🔧'),
    phoneNumber: '9443267890',
    skill: 'Plumber',
    location: 'Pollachi (பொள்ளாச்சி)',
    availability: 'Available Today',
    status: 'approved',
    bio: 'Specialist in overhead PVC tank pipe fittings, borewell motor connection leaks, and bathroom tap repairs.',
    experienceYears: 9,
    createdAt: '2026-07-12T10:00:00.000Z',
    approvedAt: '2026-07-12T14:30:00.000Z',
    averageRating: 4.9,
    reviewCount: 3,
  },
  {
    id: 'prov-03',
    fullName: 'Lakshmi Ammal (லட்சுமி அம்மாள்)',
    photoUrl: createSvgAvatar('LA', '#be185d', '#ffffff', '🧵'),
    phoneNumber: '9789012345',
    skill: 'Tailor',
    location: 'Madurai (மதுரை)',
    availability: 'Available This Week',
    status: 'approved',
    bio: 'Expert women tailor: Aari work bridal blouses, churidar sets, school uniforms, and urgent alteration work.',
    experienceYears: 15,
    createdAt: '2026-07-15T08:30:00.000Z',
    approvedAt: '2026-07-15T10:00:00.000Z',
    averageRating: 4.8,
    reviewCount: 3,
  },
  {
    id: 'prov-04',
    fullName: 'R. Ramesh (ரமேஷ்)',
    photoUrl: createSvgAvatar('RR', '#92400e', '#ffffff', '🪚'),
    phoneNumber: '9894345678',
    skill: 'Carpenter',
    location: 'Karaikudi (காரைக்குடி)',
    availability: 'Available Today',
    status: 'approved',
    bio: 'Traditional wood carpentry, door and window latch fixes, wooden cots, and kitchen modular woodwork.',
    experienceYears: 14,
    createdAt: '2026-07-18T11:00:00.000Z',
    approvedAt: '2026-07-18T13:00:00.000Z',
    averageRating: 4.9,
    reviewCount: 3,
  },
  {
    id: 'prov-05',
    fullName: 'Kavitha Teacher (கவிதா டீச்சர்)',
    photoUrl: createSvgAvatar('KT', '#15803d', '#ffffff', '📚'),
    phoneNumber: '9942189012',
    skill: 'Tutor',
    location: 'Tenkasi (தென்காசி)',
    availability: 'Available Now',
    status: 'approved',
    bio: 'B.Sc., B.Ed. Maths and Science home tuitions for 6th to 10th standard state board & CBSE students.',
    experienceYears: 8,
    createdAt: '2026-07-20T09:15:00.000Z',
    approvedAt: '2026-07-20T10:45:00.000Z',
    averageRating: 5.0,
    reviewCount: 3,
  },
  {
    id: 'prov-06',
    fullName: 'P. Kannan (கண்ணன்)',
    photoUrl: createSvgAvatar('PK', '#4338ca', '#ffffff', '⚡'),
    phoneNumber: '9444156789',
    skill: 'Electrician',
    location: 'Kumbakonam (கும்பகோணம்)',
    availability: 'Available Today',
    status: 'approved',
    bio: 'Specialist in ceiling fans, solar panel wiring, sub-meter installations, and agricultural pump repair.',
    experienceYears: 7,
    createdAt: '2026-07-25T11:20:00.000Z',
    approvedAt: '2026-07-25T12:00:00.000Z',
    averageRating: 4.8,
    reviewCount: 3,
  },
  {
    id: 'prov-07',
    fullName: 'A. Anitha (அனிதா)',
    photoUrl: createSvgAvatar('AA', '#0f766e', '#ffffff', '🧵'),
    phoneNumber: '9841278901',
    skill: 'Tailor',
    location: 'Chengalpattu (செங்கல்பட்டு)',
    availability: 'Available Now',
    status: 'approved',
    bio: 'Expert in children clothes, festive silk pavadai sattai, ladies nighties, and quick emergency alterations.',
    experienceYears: 11,
    createdAt: '2026-07-28T14:00:00.000Z',
    approvedAt: '2026-07-28T15:30:00.000Z',
    averageRating: 4.8,
    reviewCount: 3,
  },
  {
    id: 'prov-08',
    fullName: 'V. Saravanan (சரவணன்)',
    photoUrl: createSvgAvatar('VS', '#1e40af', '#ffffff', '🔧'),
    phoneNumber: '9750089123',
    skill: 'Plumber',
    location: 'Thanjavur (தஞ்சாவூர்)',
    availability: 'Available This Week',
    status: 'approved',
    bio: 'Pipeline laying for new homes, bathroom sanitary fittings, drainage blockage clearance, and RO water filter service.',
    experienceYears: 6,
    createdAt: '2026-08-01T10:00:00.000Z',
    approvedAt: '2026-08-01T11:15:00.000Z',
    averageRating: 4.8,
    reviewCount: 3,
  },
  {
    id: 'prov-09',
    fullName: 'G. Balaji (பாலாஜி)',
    photoUrl: createSvgAvatar('GB', '#78350f', '#ffffff', '🪚'),
    phoneNumber: '9894011223',
    skill: 'Carpenter',
    location: 'Pollachi (பொள்ளாச்சி)',
    availability: 'Available Today',
    status: 'approved',
    bio: 'Plywood woodwork, cupboard hinges, dining table polishing, and antique furniture restoration.',
    experienceYears: 10,
    createdAt: '2026-08-05T16:00:00.000Z',
    approvedAt: '2026-08-05T17:30:00.000Z',
    averageRating: 4.9,
    reviewCount: 2,
  },
  {
    id: 'prov-10',
    fullName: 'S. Sundaram Master (சுந்தரம் மாஸ்டர்)',
    photoUrl: createSvgAvatar('SM', '#065f46', '#ffffff', '📚'),
    phoneNumber: '9486123450',
    skill: 'Tutor',
    location: 'Dindigul (திண்டுக்கல்)',
    availability: 'Available Now',
    status: 'approved',
    bio: 'Retired government school Headmaster. English grammar, spoken English, and Tamil literature coaching.',
    experienceYears: 25,
    createdAt: '2026-08-10T08:30:00.000Z',
    approvedAt: '2026-08-10T10:00:00.000Z',
    averageRating: 4.9,
    reviewCount: 3,
  },
];

export const INITIAL_PROVIDERS: Provider[] = RAW_PROVIDERS.map((p) => ({
  ...p,
  name: p.fullName,
  phone: p.phoneNumber,
  isVisible: true,
  isPublicVisible: true,
}));

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-01',
    providerId: 'prov-01',
    rating: 5,
    comment: 'Came within 20 minutes when agricultural starter box sparked. Replaced fuse safely and tested pump.',
    reviewerName: 'Subramanian (சுப்பிரமணியன்)',
    createdAt: '2026-07-15T14:30:00.000Z',
  },
  {
    id: 'rev-02',
    providerId: 'prov-01',
    rating: 5,
    comment: 'Very polite and knowledgeable electrician. Fixed ceiling fan switch and replaced old wires.',
    reviewerName: 'Veluchamy (வேலுச்சாமி)',
    createdAt: '2026-07-22T11:00:00.000Z',
  },
  {
    id: 'rev-03',
    providerId: 'prov-01',
    rating: 4.5,
    comment: 'Good work on full house inverter backup wiring.',
    reviewerName: 'Ravi Kumar (ரவி)',
    createdAt: '2026-08-01T17:15:00.000Z',
  },
  {
    id: 'rev-04',
    providerId: 'prov-02',
    rating: 5,
    comment: 'Our overhead tank pipe had a big crack. Selvam brought all parts and resolved it in 45 minutes.',
    reviewerName: 'Marimuthu (மாரிமுத்து)',
    createdAt: '2026-07-16T12:00:00.000Z',
  },
  {
    id: 'rev-05',
    providerId: 'prov-02',
    rating: 5,
    comment: 'Excellent plumbing work. No extra charges, very honest person in Pollachi.',
    reviewerName: 'Karthik Raja (கார்த்திக்)',
    createdAt: '2026-07-28T09:40:00.000Z',
  },
  {
    id: 'rev-06',
    providerId: 'prov-02',
    rating: 4.8,
    comment: 'Good quick fix for kitchen sink blockage.',
    reviewerName: 'Gomathi (கோமதி)',
    createdAt: '2026-08-05T16:20:00.000Z',
  },
  {
    id: 'rev-07',
    providerId: 'prov-03',
    rating: 5,
    comment: 'Stitched two wedding blouses with beautiful stone embroidery right on schedule.',
    reviewerName: 'Meenakshi (மீனாட்சி)',
    createdAt: '2026-07-20T15:00:00.000Z',
  },
  {
    id: 'rev-08',
    providerId: 'prov-03',
    rating: 4.5,
    comment: 'Perfect fitting for churidar suits and school uniforms.',
    reviewerName: 'Shanthi (சாந்தி)',
    createdAt: '2026-08-02T13:10:00.000Z',
  },
  {
    id: 'rev-09',
    providerId: 'prov-03',
    rating: 5,
    comment: 'Great tailoring skills, very gentle and trustworthy.',
    reviewerName: 'Geetha (கீதா)',
    createdAt: '2026-08-10T10:30:00.000Z',
  },
  {
    id: 'rev-10',
    providerId: 'prov-04',
    rating: 5,
    comment: 'Repaired our main teak wooden entrance door latch and restored the frame neatly.',
    reviewerName: 'Alagappan (அழகப்பன்)',
    createdAt: '2026-07-25T11:45:00.000Z',
  },
  {
    id: 'rev-11',
    providerId: 'prov-04',
    rating: 5,
    comment: 'Built custom wooden pooja unit shelving. Precision work and high craftsmanship.',
    reviewerName: 'Chellappa (செல்லப்பா)',
    createdAt: '2026-08-08T14:15:00.000Z',
  },
  {
    id: 'rev-12',
    providerId: 'prov-04',
    rating: 4.8,
    comment: 'Replaced wooden window frame louvers quickly before the monsoon rain.',
    reviewerName: 'Meyyappan (மெய்யப்பன்)',
    createdAt: '2026-08-14T10:00:00.000Z',
  },
  {
    id: 'rev-13',
    providerId: 'prov-05',
    rating: 5,
    comment: 'My daughter was scared of 10th standard maths. After Kavitha teacher coaching, she scored 94%!',
    reviewerName: 'Murugesan (முருகேசன்)',
    createdAt: '2026-07-27T18:00:00.000Z',
  },
  {
    id: 'rev-14',
    providerId: 'prov-05',
    rating: 5,
    comment: 'Patient teaching, provides daily practice worksheets. Very dedicated.',
    reviewerName: 'Priya (பிரியா)',
    createdAt: '2026-08-04T19:30:00.000Z',
  },
  {
    id: 'rev-15',
    providerId: 'prov-05',
    rating: 5,
    comment: 'Best teacher in Tenkasi area for school students.',
    reviewerName: 'Sundar (சுந்தர்)',
    createdAt: '2026-08-15T16:00:00.000Z',
  },
  {
    id: 'rev-16',
    providerId: 'prov-06',
    rating: 4.5,
    comment: 'Prompt ceiling fan wiring installation in Kumbakonam.',
    reviewerName: 'Vaidyanathan (வைத்தியநாதன்)',
    createdAt: '2026-08-01T15:20:00.000Z',
  },
  {
    id: 'rev-17',
    providerId: 'prov-06',
    rating: 5,
    comment: 'Honest technician. Repaired starter coil without unnecessary parts change.',
    reviewerName: 'Balamurugan (பாலமுருகன்)',
    createdAt: '2026-08-12T11:00:00.000Z',
  },
  {
    id: 'rev-18',
    providerId: 'prov-06',
    rating: 4.8,
    comment: 'Installed sub-meter and repaired distribution board safely.',
    reviewerName: 'Swaminathan (சுவாமிநாதன்)',
    createdAt: '2026-08-20T16:15:00.000Z',
  },
  {
    id: 'rev-19',
    providerId: 'prov-07',
    rating: 5,
    comment: 'Stitched school uniform sets for my two children in two days before school reopening.',
    reviewerName: 'Poongodi (பூங்கொடி)',
    createdAt: '2026-08-03T16:30:00.000Z',
  },
  {
    id: 'rev-20',
    providerId: 'prov-07',
    rating: 4.8,
    comment: 'Neat stitching and very friendly customer service in Chengalpattu.',
    reviewerName: 'Revathi (ரேவதி)',
    createdAt: '2026-08-16T12:15:00.000Z',
  },
  {
    id: 'rev-21',
    providerId: 'prov-07',
    rating: 4.6,
    comment: 'Fast alteration of ladies suits and blouse fitting done same day.',
    reviewerName: 'Kalyani (கல்யாணி)',
    createdAt: '2026-08-22T14:40:00.000Z',
  },
  {
    id: 'rev-22',
    providerId: 'prov-08',
    rating: 5,
    comment: 'Fixed bathroom mixer tap and cleared drainage line smoothly.',
    reviewerName: 'Dhanalakshmi (தனலட்சுமி)',
    createdAt: '2026-08-08T10:00:00.000Z',
  },
  {
    id: 'rev-23',
    providerId: 'prov-08',
    rating: 4.5,
    comment: 'Quick and reliable plumbing service in Thanjavur.',
    reviewerName: 'Nagarajan (நாகராஜன்)',
    createdAt: '2026-08-20T17:40:00.000Z',
  },
  {
    id: 'rev-24',
    providerId: 'prov-08',
    rating: 5,
    comment: 'Installed overhead water tank bypass valve properly. No leaks.',
    reviewerName: 'Saradha (சாரதா)',
    createdAt: '2026-08-23T11:20:00.000Z',
  },
  {
    id: 'rev-25',
    providerId: 'prov-09',
    rating: 5,
    comment: 'Replaced modular kitchen cabinet hinges and adjusted all doors perfectly.',
    reviewerName: 'Sivakumar (சிவகுமார்)',
    createdAt: '2026-08-10T14:30:00.000Z',
  },
  {
    id: 'rev-26',
    providerId: 'prov-09',
    rating: 4.8,
    comment: 'Great polish finish on our 20-year-old rosewood armchairs.',
    reviewerName: 'Dhandapani (தண்டபாணி)',
    createdAt: '2026-08-21T09:15:00.000Z',
  },
  {
    id: 'rev-27',
    providerId: 'prov-10',
    rating: 5,
    comment: 'Helped my son pass 12th standard English with 88 marks. Excellent teacher.',
    reviewerName: 'Karuppasamy (கருப்பசாமி)',
    createdAt: '2026-08-15T18:00:00.000Z',
  },
  {
    id: 'rev-28',
    providerId: 'prov-10',
    rating: 5,
    comment: 'Strict discipline yet very kind and encouraging. Wonderful grammar foundation.',
    reviewerName: 'Anandhi (ஆனந்தி)',
    createdAt: '2026-08-22T17:30:00.000Z',
  },
  {
    id: 'rev-29',
    providerId: 'prov-10',
    rating: 4.8,
    comment: 'Respected educator in Dindigul town. Very helpful for competitive school exams.',
    reviewerName: 'Palaniappan (பழனியப்பன்)',
    createdAt: '2026-08-25T11:45:00.000Z',
  },
];
